config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get "home/about"
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/potatos_helper.rb
module PotatosHelper
end

app/views/friends/_form.html.erb
<h1 class="w-full text-4xl font-medium text-left leading-snug font-serif"><%= local_assigns[:title] %></h1>
<%= form_with(model: friend, class:"flex flex-col items-start justify-start pt-10 pr-10 pb-10 pl-10 bg-white shadow-2xl rounded-xl relative z-10") do |form| %>
  <div class="flex flex-col gap-8 w-full mt-6 mr-0 mb-0 ml-0 relative">
    <div class="relative">
      <%= form.label :first_name, class:"bg-white pt-0 pr-2 pb-0 pl-2 -mt-3 mr-0 mb-0 ml-2 font-medium text-gray-600 absolute" %>
      <%= 
        form.text_field :first_name,
        placeholder: "Max", 
        class:"border placeholder-gray-400 focus:outline-none
          focus:border-black w-full pt-4 pr-4 pb-4 pl-4 mt-2 mr-0 mb-0 ml-0 text-base block bg-white
          border-gray-300 rounded-md
        " 
      %>
    </div>
    <div class="relative">
      <%= form.label :last_name, class:"bg-white pt-0 pr-2 pb-0 pl-2 -mt-3 mr-0 mb-0 ml-2 font-medium text-gray-600 absolute" %>
      <%= 
        form.text_field :last_name, 
        placeholder: "Oselola", 
        class:"border placeholder-gray-400 focus:outline-none
          focus:border-black w-full pt-4 pr-4 pb-4 pl-4 mt-2 mr-0 mb-0 ml-0 text-base block bg-white
          border-gray-300 rounded-md
        " 
      %>
    </div>
    <div class="relative">
      <%= form.label :email, class:"bg-white pt-0 pr-2 pb-0 pl-2 -mt-3 mr-0 mb-0 ml-2 font-medium text-gray-600 absolute" %>
      <%= 
        form.text_field :email,
        placeholder: "email@example.com",  
        class:"border placeholder-gray-400 focus:outline-none
          focus:border-black w-full pt-4 pr-4 pb-4 pl-4 mt-2 mr-0 mb-0 ml-0 text-base block bg-white
          border-gray-300 rounded-md
        " 
      %>
    </div>
    <div class="relative">
      <%= form.label :Phone, class:"bg-white pt-0 pr-2 pb-0 pl-2 -mt-3 mr-0 mb-0 ml-2 font-medium text-gray-600 absolute" %>
      <%= 
        form.text_field :phone,
        placeholder: "555555555",   
        class:"border placeholder-gray-400 focus:outline-none
          focus:border-black w-full pt-4 pr-4 pb-4 pl-4 mt-2 mr-0 mb-0 ml-0 text-base block bg-white
          border-gray-300 rounded-md
        " 
      %>
    </div>
    <div class="relative">
      <%= form.label :twitter, class:"bg-white pt-0 pr-2 pb-0 pl-2 -mt-3 mr-0 mb-0 ml-2 font-medium text-gray-600 absolute" %>
      <%= 
        form.text_field :twitter,
        placeholder: "@twitter", 
        class:"border placeholder-gray-400 focus:outline-none
          focus:border-black w-full pt-4 pr-4 pb-4 pl-4 mt-2 mr-0 mb-0 ml-0 text-base block bg-white
          border-gray-300 rounded-md
        " 
      %>
    </div>
    <div class="relative self-end">
      <%= form.submit class: "bg-red-700 px-4 py-3 rounded-md hover:cursor-pointer text-white focus:ring-2 focus:ring-offset-2 focus:ring-red-700 outline-none transition-all hover:bg-red-800" %>
    </div>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<tr>
  <td class="py-3 px-4">
    <%= link_to friend.first_name + ' ' + friend.last_name, friend, class:"hover:underline" %>
  </td>
  <td class="py-3 px-4"><%= friend.email %></td>
  <td class="py-3 px-4"><%= friend.phone %></td>
  <td class="py-3 px-4"><%= friend.twitter %></td>
</tr>

app/views/friends/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", friend: @friend, title: "Edit friend" %>

  <div class="flex items-center justify-end gap-4 mt-3">
    <%= link_to "Show this friend", @friend, class: "underline text-white" %>
    <%= link_to "Back to friends", friends_path, class: "underline text-white" %>
  </div>
</div>

app/views/friends/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <div class="p-4 bg-white rounded-lg flex flex-col" id="notice">
      <p class="font-medium">Alert<p>
      <p><%= notice %></p>
    </div>
  <% end %>
  <h1 class="text-4xl font-medium text-left leading-snug font-serif text-white">Friends</h1>
  <% if @friends.any? %>
    <div id="friends" class="min-w-full flex items-center justify-center">
      <table class="min-w-full bg-white rounded-xl">
        <thead class="border-b border-blue-gray-200">
          <tr class="bg-blue-gray-100 text-gray-700">
            <th class="py-3 px-4 text-left font-medium">Name</th>
            <th class="py-3 px-4 text-left font-medium">E-mail</th>
            <th class="py-3 px-4 text-left font-medium">Phone</th>
            <th class="py-3 px-4 text-left font-medium">Twitter</th>
          </tr>
        </thead>
        <tbody class="text-blue-gray-900 divide-y divide-blue-gray-200">
          <%= render @friends %>
        </tbody>
      </table>
    </div>
  <% else %>
    <p class="text-white">There are no friends to show.</p>
  <% end %>
  <%= link_to "New friend", new_friend_path, class: "block underline text-white mt-4 text-left" %>
</div>

app/views/friends/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", friend: @friend, title: "New friend" %>
  <%= link_to "Back to friends", friends_path, class: "block mt-3 underline text-white w-full text-right" %>
</div>

app/views/friends/show.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <% if notice.present? %>
    <div class="p-4 bg-white rounded-lg flex flex-col" id="notice">
      <p class="font-medium">Alert<p>
      <p><%= notice %></p>
    </div>
  <% end %>
  <div class="bg-white p-4 rounded-lg w-full mt-4">
    <h1 class="w-full text-4xl font-medium text-left leading-snug font-serif"><%= @friend.first_name + " " + @friend.last_name %></h1>  
    <div class="relative">
      <label class="bg-white pt-0 pr-2 pb-0 pl-2 -mt-3 mr-0 mb-0 ml-2 font-medium text-gray-600 absolute">
        Name
      </label>
      <span 
        class="
          border placeholder-gray-400 focus:outline-none focus:border-black w-full pt-4 pr-4 pb-4 
          pl-4 mt-2 mr-0 mb-0 ml-0 text-base block bg-whiteborder-gray-300 rounded-md
        " 
      >
        <%= @friend.first_name + " " + @friend.last_name %>
      </span>
    </div>
    <div class="relative">
      <label class="bg-white pt-0 pr-2 pb-0 pl-2 -mt-3 mr-0 mb-0 ml-2 font-medium text-gray-600 absolute">
        E-mail
      </label>
      <span 
        class="
          border placeholder-gray-400 focus:outline-none focus:border-black w-full pt-4 pr-4 pb-4 
          pl-4 mt-2 mr-0 mb-0 ml-0 text-base block bg-whiteborder-gray-300 rounded-md
        " 
      >
        <%= @friend.email %>
      </span>
    </div>
    <div class="relative">
      <label class="bg-white pt-0 pr-2 pb-0 pl-2 -mt-3 mr-0 mb-0 ml-2 font-medium text-gray-600 absolute">
        Phone
      </label>
      <span 
        class="
          border placeholder-gray-400 focus:outline-none focus:border-black w-full pt-4 pr-4 pb-4 
          pl-4 mt-2 mr-0 mb-0 ml-0 text-base block bg-whiteborder-gray-300 rounded-md
        " 
      >
        <%= @friend.phone %>
      </span>
    </div>
  </div>
  <div class="flex items-center justify-end gap-4 mt-3">
    <%= link_to "Edit this friend", edit_friend_path(@friend), class: "underline text-white" %>
    <%= button_to "Destroy this friend", friend_path(@friend), method: :delete, class: "underline text-white" %>
    <%= link_to "Back to friends", friends_path, class: "underline text-white" %>
  </div>
</div>

app/views/home/about.html.erb
<p class="text-lg text-white text-left flex-1">This is an about page!</p>

app/views/home/index.html.erb
<p class="text-lg text-white text-left flex-1">This is your friend managing app!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friend App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="max-w-screen w-full h-screen bg-zinc-900 flex flex-col">
      <%= render "shared/header" %>
      <main class="flex justify-center flex-1 px-16 py-8">
        <%= yield %>
      </main>
      <footer class="flex items-center justify-center w-full p-2 bg-red-700">
        <span class="text-white">&copy; 2024 Friend App</span>
      </footer>
    </main>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="antialiased bg-gray-100 dark-mode:bg-gray-900">
  <div class="w-full text-gray-700 bg-white dark-mode:text-gray-200 dark-mode:bg-gray-800">
    <div class="flex flex-col mx-16 md:items-center md:justify-between md:flex-row">
      <%= 
        link_to "Friend App", 
        root_path,
        class:"text-lg font-semibold tracking-widest py-4 text-gray-900 uppercase 
          rounded-lg dark-mode:text-white focus:outline-none focus:shadow-outline
        "    
      %> 
      <nav class="flex-col flex-grow hidden pb-4 md:pb-0 md:flex md:justify-end md:flex-row">
        <%=
          link_to "Home",
          root_path,
          class:"px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent
            dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white 
            dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 
            focus:outline-none focus:shadow-outline
          " 
        %>
        <%= 
          link_to "About us",
          home_about_path, 
          class:"px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent
            dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white 
            dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 
            focus:outline-none focus:shadow-outline
          "  
        %> 
        <% if user_signed_in? %>
          <%=
            link_to "Friends",
            friends_path,
            class:"px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent
              dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white 
              dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 
              focus:outline-none focus:shadow-outline
            " 
          %>
          <%=
            link_to "Add friend",
            new_friend_path,
            class:"px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent
              dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white 
              dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 
              focus:outline-none focus:shadow-outline
            " 
          %>
          <%=
            link_to "Edit profile",
            edit_user_registration_path,
            class:"px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent
              dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white 
              dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 
              focus:outline-none focus:shadow-outline
            " 
          %>
          <%=
            link_to "Sign out",
            destroy_user_session_path,
            method: :delete,
            class:"px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent
              dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white 
              dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 
              focus:outline-none focus:shadow-outline
            " 
          %>
        <% else %>
          <%=
            link_to "Sign in",
            new_user_session_path,
            class:"px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent
              dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white 
              dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 
              focus:outline-none focus:shadow-outline
            " 
          %>
          <%=
            link_to "Sign up",
            new_user_registration_path,
            class:"px-4 py-2 mt-2 text-sm font-semibold bg-transparent rounded-lg dark-mode:bg-transparent
              dark-mode:hover:bg-gray-600 dark-mode:focus:bg-gray-600 dark-mode:focus:text-white dark-mode:hover:text-white 
              dark-mode:text-gray-200 md:mt-0 md:ml-4 hover:text-gray-900 focus:text-gray-900 hover:bg-gray-200 focus:bg-gray-200 
              focus:outline-none focus:shadow-outline
            " 
          %>  
        <% end %>
      </nav>
    </div>
  </div>
</div>